global:
  smtp_smarthost: 'ssmtp:465'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'user'
  smtp_auth_password: 'password'
  smtp_require_tls: false

route:
  # どの match ルールにもひっかからなかったものの送り先
  receiver: 'catch-all'

  # group_by で alert をまとめる単位を指定することができる
  group_by: ['alertname', 'cluster']

  # group 単位で最初のアラートを送信するまでの待ち時間
  # 一気に沢山のアラートが発生した場合に沢山の通知を送ってしまわないようにする
  # その分通知が遅延するわけではある
  group_wait: 10s

  # group_interval を超えたら同じグループの通知でも送られる
  group_interval: 5m

receivers:
  - name: 'catch-all'
    email_configs:
      - to: 'recipient@example.com'
        send_resolved: true
        tls_config:
          insecure_skip_verify: true
    # 1つの receiver に複数の通知先を指定可能 (email と webhook とか)
    webhook_configs:
      - url: http://webhook:5001/
        send_resolved: true
        #http_config:
        #  basic_auth:
        #    username: xxx
        #    password: yyy

# critical 状態のところに warning が来ても通知しない
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
